stages:
  - build
  - deploy

variables:
  IMAGE_NAME: home-manager
  CONTAINER_NAME: home-manager
  PORT: 9300

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  script:
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker run -d --name $CONTAINER_NAME -p $PORT:$PORT -e DATABASE_URL=$DATABASE_URL -e MQTT_URL=$MQTT_URL $IMAGE_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'



